name: Upload & Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: upload-deploy-group
    steps:
      - uses: actions/checkout@v4

      - name: rsync caddyfile to server
        uses: burnett01/rsync-deployments@7.0.1 # takeout the shell script and use it directly?
        # and script needs hostname authentication as well.
        with:
          switches: -avzr --delete
          path: Caddyfile
          remote_path: /home/a/caddy
          remote_host: ${{ secrets.SERVER_IP }}
          remote_user: a
          remote_key: ${{ secrets.SERVER_RSA_PRIV_KEY }}

      - name: rsync script to server
        uses: burnett01/rsync-deployments@7.0.1 # takeout the shell script and use it directly?
        # and script needs hostname authentication as well.
        with:
          switches: -avzr --delete
          path: deploycaddy.sh
          remote_path: /home/a
          remote_host: ${{ secrets.SERVER_IP }}
          remote_user: a
          remote_key: ${{ secrets.SERVER_RSA_PRIV_KEY }}

      - name: caddy reload
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: a
          key: ${{ secrets.SERVER_RSA_PRIV_KEY }}
          script: /home/a/deploycaddy.sh